### ISSUE TITLE
Real-life git annex stalls

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-osf#135]
A severe test stall on Windows has been surfacing in PRs for the past months until I downgraded git-annex to a version we had been using successfully on a real machine in our office in #128. I now have a brand new Windows computer for testing, with git-annex from August, and I can reproduce the test stalls locally:

<details><summary>System set up</summary>

```
(base) C:\Users\datalad>datalad wtf
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials
  - keyring:
    - active_backends:
      - Windows WinVaultKeyring
      - Windows RegistryKeyring
      - EncryptedKeyring with not defined v.1.0 at C:\Users\datalad\AppData\Local\Python Keyring\wincrypto_pass.cfg
      - PlaintextKeyring with no encyption v.1.0 at C:\Users\datalad\AppData\Local\Python Keyring\keyring_pass.cfg
    - config_file: C:\Users\datalad\.config\python_keyring\keyringrc.cfg
    - data_root: C:\Users\datalad\AppData\Local\Python Keyring
## datalad
  - full_version: 0.13.4.dev337-gf66d-dirty
  - version: 0.13.4.dev337
## dependencies
  - annexremote: 1.4.3
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:7z: 19.00
  - cmd:annex: 8.20200815-g335aae266
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.28.0.windows.1
  - cmd:system-git: 2.28.0.windows.1
  - cmd:system-ssh: for
  - humanize: 3.0.1
  - iso8601: 0.1.13
  - keyring: 21.4.0
  - keyrings.alt: 4.0.0
  - msgpack: 1.0.0
  - requests: 2.23.0
  - wrapt: 1.12.1
## environment
  - PATH: C:\Users\datalad\miniconda3;C:\Users\datalad\miniconda3\Library\mingw-w64\bin;C:\Users\datalad\miniconda3\Library\usr\bin;C:\Users\datalad\miniconda3\Library\bin;C:\Users\datalad\miniconda3\Scripts;C:\Users\datalad\miniconda3\bin;C:\Users\datalad\miniconda3\condabin;.;C:\Users\datalad\miniconda3\Library\ImageMagick-7.0.10-Q16-HDRI;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Users\datalad\AppData\Local\Microsoft\WindowsApps;C:\ProgramFiles\7-Zip;.
## extensions
  - osf:
    - description: DataLad extension for OSF support
    - entrypoints:
      - datalad_osf.create_sibling_osf.CreateSiblingOSF:
        - class: CreateSiblingOSF
        - load_error: None
        - module: datalad_osf.create_sibling_osf
        - names:
          - create-sibling-osf
          - create_sibling_osf
      - datalad_osf.credentials.OSFCredentials:
        - class: OSFCredentials
        - load_error: None
        - module: datalad_osf.credentials
        - names:
          - osf-credentials
          - osf_credentials
    - load_error: None
    - module: datalad_osf
    - version: 0.2.0+8.g30ab6f6.dirty
## git-annex
  - build flags:
    - Assistant
    - Webapp
    - Pairing
    - S3
    - WebDAV
    - TorrentParser
    - Feeds
    - Testsuite
  - dependency versions:
    - aws-0.21.1
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.4
    - feed-1.2.0.1
    - ghc-8.6.5
    - http-client-0.5.14
    - persistent-sqlite-2.9.3
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0.1
  - key/value backends:
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: mingw32 x86_64
  - remote types:
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - hook
    - external
  - supported repository versions:
    - 8
  - upgrade supported from repository versions:
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20200815-g335aae266
## location
  - path: C:\Users\datalad
  - type: directory
## metadata_extractors
  - annex (datalad 0.13.4):
    - distribution: datalad 0.13.4
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio (datalad 0.13.4):
    - distribution: datalad 0.13.4
    - load_error: No module named 'mutagen' [audio.py:<module>:17]
    - module: datalad.metadata.extractors.audio
  - datacite (datalad 0.13.4):
    - distribution: datalad 0.13.4
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core (datalad 0.13.4):
    - distribution: datalad 0.13.4
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822 (datalad 0.13.4):
    - distribution: datalad 0.13.4
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif (datalad 0.13.4):
    - distribution: datalad 0.13.4
    - load_error: No module named 'exifread' [exif.py:<module>:16]
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage (datalad 0.13.4):
    - distribution: datalad 0.13.4
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image (datalad 0.13.4):
    - distribution: datalad 0.13.4
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp (datalad 0.13.4):
    - distribution: datalad 0.13.4
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## metadata_indexers
## python
  - implementation: CPython
  - version: 3.8.3
## system
  - distribution: msys_nt-10.0/2.5.0  10/10.0.19041/SP0/Multiprocessor Free
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: cp1252
  - max_path_length: 259
  - name: Windows
  - release: 10
  - type: nt
  - version: 10.0.19041
```

</details>

<details><summary>Here's a snip from testing debug output </summary>
```
[DEBUG] Process 12360 started
[DEBUG] Waiting for process 12360 to complete
[DEBUG] Process 12360 exited with return code 0
[DEBUG] Determined class of decorated function: <class 'datalad_osf.create_sibling_osf.CreateSiblingOSF'>
[DEBUG] Resolved dataset for create OSF remote: C:\Users\datalad\AppData\Local\Temp\datalad_temp_tree_epm3fq8d
[DEBUG] Determined class of decorated function: <class 'datalad.distribution.siblings.Siblings'>
[DEBUG] Resolved dataset for sibling configuration: C:\Users\datalad\AppData\Local\Temp\datalad_temp_tree_epm3fq8d
[DEBUG] Async run ['git', 'config', '-z', '-l', '--show-origin']
[DEBUG] Launching process ['git', 'config', '-z', '-l', '--show-origin']
[DEBUG] Process 4876 started
[DEBUG] Waiting for process 4876 to complete
[DEBUG] Process 4876 exited with return code 0
[DEBUG] Async run ['git', 'annex', 'initremote', '-c', 'annex.dotfiles=true', '-c', 'annex.retry=3', 'osf-storage', 'encryption=none', 'type=external', 'externaltype=osf', 'autoenable=true', 'node=smb3x', 'exporttree=yes']
[DEBUG] Launching process ['git', 'annex', 'initremote', '-c', 'annex.dotfiles=true', '-c', 'annex.retry=3', 'osf-storage', 'encryption=none', 'type=external', 'externaltype=osf', 'autoenable=true', 'node=smb3x', 'exporttree=yes']
[DEBUG] Process 4892 started
[DEBUG] Waiting for process 4892 to complete
[DEBUG] Process 4892 exited with return code 0
[DEBUG] Async run ['git', 'config', '-z', '-l', '--show-origin']
[DEBUG] Launching process ['git', 'config', '-z', '-l', '--show-origin']
[DEBUG] Process 2896 started
[DEBUG] Waiting for process 2896 to complete
[DEBUG] Process 2896 exited with return code 0
create-sibling-osf(ok): https://osf.io/smb3x/
[DEBUG] Async run ['git', 'annex', 'export', 'HEAD', '--to', 'osf-storage']
[DEBUG] Launching process ['git', 'annex', 'export', 'HEAD', '--to', 'osf-storage'] 
[DEBUG] Process 6408 started
[DEBUG] Waiting for process 6408 to complete
[we're hanging here]
```

</details>

While hanging, there is a git-annex-remote-osf.exe process in the task manager, and this process spends its days listening to the special remote:
<img width="667" alt="annex-osf-remote" src="https://user-images.githubusercontent.com/29738718/96720044-8e6fed00-13aa-11eb-82c5-c82cfb238bfe.png">

The line in question, 855 in annex remote, is oddly similar to the problematic line that causes stalling and breakage in the datalad-archives special remote for me in https://github.com/datalad/datalad/issues/5015

```
line = self.input.readline()
```

<details><summary>For reference, here's the function it is in </summary>

```
    def Listen(self, input=sys.stdin):
        """
        Listen on `input` for messages from git annex.

        Parameters
        ----------
        input : io.TextIOBase
            Where to listen for git-annex request messages.
            Default: sys.stdin

        Raises
        ----------
        NotLinkedError
            If there is no remote linked to this master.
        """
        if not (hasattr(self, 'remote') and hasattr(self, 'protocol')):
            raise NotLinkedError("Please execute LinkRemote(remote) first.")

        self.input = input
        self._send(self.protocol.version)
        while True:
            # due to a bug in python 2 we can't use an iterator here: https://bugs.python.org/issue1633941
            line = self.input.readline()
            if not line:
                break
            line = line.rstrip()
            try:
                reply = self.protocol.command(line)
                if reply:
                    self._send(reply)
            except (UnsupportedRequest):
                self._send ("UNSUPPORTED-REQUEST")
            except (NotImplementedError):
                self._send ("ERROR not yet implemented")
                raise SystemExit
            #except Exception as e:
            #    self._send ("ERROR", e)
            #    raise SystemExit
```

</details>
